### ISSUE TITLE
Hapi new version

### ISSUE THREAD

**Issue by mr-fool** [bradtraversy/hapiapp#1]
Basically I am trying to follow along your tutorial video and a lot has changed. I am currently stuck at the mongoose part
https://github.com/mr-fool/hapiJS/blob/master/app.js#L48
I got this whenever I try to refresh http://localhost:8000/tasks
> [nodemon] restarting due to changes...
> [nodemon] starting `node app.js`
> Server running at: http://localhost:8000
> MongoDB connected...
> Debug: internal, implementation, error
>     Error: handler method did not return a value, a promise, or throw an error
>     at module.exports.internals.Manager.execute (/Users/hetzer/Documents/hapiapp/node_modules/hapi/lib/toolkit.js:52:29)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> [ { _id: 5c3bef38f9849c0434facda1, text: 'My Task One' } ]

![screen shot 2019-01-13 at 8 52 03 pm](https://user-images.githubusercontent.com/6241984/51095869-1a37fc80-1775-11e9-93b7-346e9cea3003.png)
Help plz

**Comment by kaushal602** [comment]
we have same error please help
